### ISSUE TITLE
Missing `helm init` before `helm package`

### ISSUE THREAD

**Issue by MaxDaten** [cathive/concourse-chartmuseum-resource#1]
Hi there,

thanks for your work in this concourse plugin. I'm currently trying to package a helm chart via a directory and push it into our chartmuseum. But while doing this, the concourse step is failing with this error:

```log
Processing chart at "/tmp/build/put/git/deployments/helm/mychart"...
Performing "helm package"...
Error: stat /root/.helm/repository/local: no such file or directory

Packaging of chart file failed.
```

This is my `put` step:

```yaml
- put: mychart
    params:
      chart: git/deployments/helm/mychart
```

I found this issue: https://github.com/helm/helm/issues/1732

So technically a `helm init --client-only` is required before executing any helm command. So is it possible to run init before package?

Thanks in advance.

**Comment by headcr4sh** [comment]
Reviewed your PR and just merged it. Thanks for the contribution. I haven't had the chance to work on the chartmuseum-resource for quite some time now so I am pretty sure it contains tons of bugs and gotchas...
