### ISSUE TITLE
Release new 0.9.0 version

### ISSUE THREAD

**Issue by Rambatino** [cathive/concourse-chartmuseum-resource#12]
I've noticed a new update under latest appears here:

![image](https://user-images.githubusercontent.com/3631109/76166225-f2fc7580-6154-11ea-9f81-d42f7183de6c.png)

But there isn't an associated specifically tagged build.

Is there a reason for this, as ideally I'd be using a specific tag for reproducibility.

**Comment by headcr4sh** [comment]
Hi @Rambatino,

I just haven't found the time (yet) to cut a new release. I hope to find the time necessary during the next few days.

**Comment by Rambatino** [comment]
Thanks! 👍
