### ISSUE TITLE
Update for Helm3

### ISSUE THREAD

**Issue by mtharrison** [cathive/concourse-chartmuseum-resource#16]
I would like to use this to push Helm3 packages. However at the moment it does not work as `helm inspect` will fail with error: `Error: apiVersion 'v2' is not valid. The value must be "v1"`

Any plans to update?

**Comment by headcr4sh** [comment]
I am thinking about a breaking change, where we'll be dropping Helm2 support entirely.
I have scheduled this change for the next major release, which will then -- finally -- be `1.0.0`.

If anyone provides a working PR, I'll gladly merge it asap.
I probably won't find the time to work on this project during the next few days...

**Comment by doughoke** [comment]
I can fix this. My fix will break things. I looked through the code and the helm cli calls either have been deprecated in v3 or have more switches.  I think some of your TS code out.ts (you are looping) does not work.  I will make change(s) on my fork and submit a PR if you are still interested.  If not (or you do not have enough time) I can make the docker image in my dockerhub until you can review.

More to come...

**Comment by doughoke** [comment]
pull request submitted.  https://github.com/cathive/concourse-chartmuseum-resource/pull/20

I have a stand alone dockerimage @ docker pull doughoke/concourse-chartmuseum-resource:v1.0.0 to test.

Ran it against concourse 6.6.0 pushed to harbor v2.1.1. No gpg signing - you may want to test it.  I looked at test logic and I decided not to touch the docker-compose logic without input.

**Comment by headcr4sh** [comment]
Thanks for the PR, @doughoke.
The next release (`v1.0.0`) will contain your changes.
