### ISSUE TITLE
When chart already exists in chartmuseum, resource should not fail with non-zero error code

### ISSUE THREAD

**Issue by ralekseenkov** [cathive/concourse-chartmuseum-resource#5]
Right now what happens is:

```
Processing chart at "/tmp/build/put/docs-chart/xxx"...
Performing "helm package"...
Inspecting chart file: "/tmp/tmp-8tF1cIeYCVjUS/xxx-0.3.2.tgz"...
Uploading chart file: "/tmp/tmp-8tF1cIeYCVjUS/xxx-0.3.2.tgz"...
An error occured while uploading the chart: "409 - Conflict".
```

The expectation is that behavior should be idempotent. Sometimes you'd want to re-run a job from Concourse and expect it to be green. I.e. you re-push same chart with the same version - nothing bad should happen.

Right now a lot of jobs are red on Concourse dashboard because of this. Alternatively, have a way to control that behavior (e.g. introduce a flag 'fail_on_conflict', etc.) and set it to 'false' by default.

**Comment by headcr4sh** [comment]
If the sources of the Helm chart have *not* been changed, there is no point in trying to upload them again, I guess. So -- basically -- this sound like a problem with the pipeline's architecture.

Unfortunately, there is no built-in mechanism in Concourse that would allow us to have outputs be triggered only under certain circumstances, so the suggested change (a flag `fail_on_conflict` sounds o.k. to me, even though I would prefer a `replace_existing` flag that would perform a check prior to uploading a changed version... new chart museum instance offer the possibility to force-upload/replace existing charts!) is a workaround that doesn't cover all use-cases.

There is one gotcha for example: if the contents of the Helm chart *has* been changed even though the version hasn't been touched and replacement of the version in the Chart Museum repository fails and is ignored silently, bad things will happen, e.g.:
- a following job might pull in the helm chart in it's `get` steps - the content's though has not been updated and you will wonder why the real new helm chart which was uploaded without any errors (well... with errors ignored I should say) is not used for deployments.

**Two quick workarounds which might help you right now:**
1) Chart Museum can be re-configured to allow re-uploads (command line flag: `--allow-overwrite`)
2) You can wrap your 'put' steps in a 'try' block: https://concourse-ci.org/try-step.html
3) If using Git to pull in your stuff, consider using the `paths` argument in your "helm chart package jobs" to ensure that only changes to the helm charts would trigger an upload (applicable if hosting all your stuff in a big mono repo)

Looking forward to hearing your feedback.

**Comment by headcr4sh** [comment]
I have provided another way that might mitigate your problem.
Have a look at the new `force` parameter. Might be a viable workaround for your situation.

**Comment by ralekseenkov** [comment]
thank you! I think the combination of "force" in this resource and "allow-overwrite" in ChartMuseum should allow to control the behavior on both sides. 

just to clarify - our pipeline architecture is totally fine (we are watching the right set of files, and we don't want to swallow failures by the 'try' step), we just want *idempotent* behavior. there may be many cases when you'd want to re-run a job and you don't want it to fail. examples would be: nightly trigger, manual trigger, change to Chart readme file, and so on. always nice when you can re-run and have green status on the dashboard.

**Comment by headcr4sh** [comment]
I am closing this issue.

If the provided mitigation path (the combination of "force" in this resource and "allow-overwrite" in ChartMuseum) causes any more problems, feel free to re-open it.

**Comment by ralekseenkov** [comment]
sounds good. thank you!
